### ISSUE TITLE
Uplink page "unpause/pause uplink queue" buttons do not work 

### ISSUE THREAD

**Issue by saba-ja** [nasa/fprime-gds#20]
| | |
|:---|:---|
|**_F´ Version_**| F' GDS 2.0 |
|**_Affected Component_**|  Uplink |
---
## Problem Description

In uplink page the unpause button does not change to pause button when uplink starts.
I manually removed v-if from the JS to enable pause button in the GUI and observed that pressing pause button cancels all running uplinks.

## How to Reproduce

1. Uplink one or several large file
2. Press the unpause button
3. Observe the unpause button does not change to pause button automatically.

## Expected Behavior

Unpause uplink queue button should change to Pause uplink queue when uplink is running.
The Pause uplink should pause the uplink instead of cancelling all the uplink queues.

**Comment by LeStarch** [comment]
I fixed the "pause" button not switching.  However, the cancel-active file is working as intended.  This is because the user most likely will pause during a transfer error.....and that means the current upload is likely invalid.  Thus we cancel the active file and proceed onto the next file when unpaused as the user will likely need to intervene on the botched file anyway.
